name: LifeSteal
version: 1.0
main: com.stormai.plugin.Main
api-version: 1.20
commands:
  lifesteal:
    description: LifeSteal plugin commands
    usage: /lifesteal [withdraw <amount>]
permissions:
  lifesteal.use:
    description: Allows use of lifesteal commands
    default: true